spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bisproject?serverTimezone=Asia/Seoul
#    url: jdbc:mariadb://localhost:3307/bisproject?serverTimezone=Asia/Seoul
    username: bis
    password: Qordlstn0417#